### ISSUE TITLE
Possible missing plugin

### ISSUE THREAD

**Issue by drid** [dl9rdz/rdzwx-go#13]
```Using cordova-fetch for cordova-android@^10.1.2
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: de.dl9rdz
	Name: rdzSonde
	Activity: MainActivity
	Android target: android-30
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.2
Discovered plugin "cordova-plugin-androidx-adapter". Adding it to the project
Installing "cordova-plugin-androidx-adapter" for android
Adding cordova-plugin-androidx-adapter to package.json
Discovered plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for android
Adding cordova-plugin-inappbrowser to package.json
Discovered plugin "de-dl9rdz-rdzwx". Adding it to the project
Command failed with exit code 1: npm view de-dl9rdz-rdzwx --json
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/de-dl9rdz-rdzwx - Not found
npm ERR! 404 
npm ERR! 404  'de-dl9rdz-rdzwx@latest' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
{
  "error": {
    "code": "E404",
    "summary": "Not Found - GET https://registry.npmjs.org/de-dl9rdz-rdzwx - Not found",
    "detail": "\n 'de-dl9rdz-rdzwx@latest' is not in this registry.\nYou should bug the author to publish it (or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}
```

**Comment by dl9rdz** [comment]
Not sure what is the problem here. It always worked for me.
The plugin should be pulled in from github due to this:
https://github.com/dl9rdz/rdzwx-go/blob/066e455ab63193d1daabec4c435926689b39a4a6/package.json#L30

**Comment by drid** [comment]
I was able to build by removing ```"de-dl9rdz-rdzwx": {}```  from cordova/plugins but I am not sure this is correct.
```
     "plugins": {
       "cordova-plugin-androidx-adapter": {},
-      "cordova-plugin-inappbrowser": {},
-      "de-dl9rdz-rdzwx": {}
+      "cordova-plugin-inappbrowser": {}
     },
```
Build:
```
Using cordova-fetch for cordova-android@^10.1.2
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: de.dl9rdz
	Name: rdzSonde
	Activity: MainActivity
	Android target: android-30
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.2
Discovered plugin "cordova-plugin-androidx-adapter". Adding it to the project
Installing "cordova-plugin-androidx-adapter" for android
Adding cordova-plugin-androidx-adapter to package.json
Discovered plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for android
Adding cordova-plugin-inappbrowser to package.json
cordova-plugin-androidx-adapter: Processed 7 source files in 302ms

```
Changing this :
```
-      "de-dl9rdz-rdzwx": {}
+      "rdzwx-plugin": {}
```
produces :
```Installing "cordova-plugin-inappbrowser" for android
Installing "de-dl9rdz-rdzwx" for android
Error during processing of action! Attempting to revert...
Failed to install 'de-dl9rdz-rdzwx': CordovaError: Uh oh!
"/home/drid/Devel/Contribute/rdzwx-go/plugins/de-dl9rdz-rdzwx/src/android/libs/mapsforge-core-master-0.16.0.jar" not found!
    at copyFile (/home/drid/Devel/Contribute/rdzwx-go/node_modules/cordova-android/lib/pluginHandlers.js:208:36)
    at install (/home/drid/Devel/Contribute/rdzwx-go/node_modules/cordova-android/lib/pluginHandlers.js:52:13)
    at ActionStack.process (/home/drid/Devel/Contribute/rdzwx-go/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/drid/Devel/Contribute/rdzwx-go/node_modules/cordova-common/src/PluginManager.js:112:24)
    at PluginManager.addPlugin (/home/drid/Devel/Contribute/rdzwx-go/node_modules/cordova-common/src/PluginManager.js:142:21)
    at /home/drid/Devel/Contribute/rdzwx-go/node_modules/cordova-android/lib/Api.js:153:78
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Uh oh!


```

**Comment by CT2IRJ** [comment]
Hi,

I'm having the same issue, tried also the solution above to no avail.

Has anyone been able to remove the test "dummy" sonde and compile?

Thanks
